#
# picoSH build environment
#

FROM eczarny/picosh-base

# dwm dependencies
RUN apt-get -y install libx11-dev:armhf >/dev/null

# Set the docker user
USER docker

# Build environment variables
ENV VERSION=3b699c1
ENV SRC=$PICOSH_STAGING/src-slstatus-${VERSION}

# Prepare the build environment
RUN mkdir -p $SRC

# Download slstatus
RUN git clone git://git.suckless.org/slstatus $SRC
